jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a command with arguments
        run: echo "${{ inputs.message }}"
        with:
          message: "Hello from GitHub Actions"
